spring:
  datasource:
    url: jdbc:postgresql://data.leenit.cf:45432/postgres
    username : kiomnd2
    password : qwer1234!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
